[package]
name = "procmon-oprs"
version = "0.18.1"
authors = ["Laurent Pelecq <lpelecq+rust@circoise.eu>"]
description = "A process monitor for Linux"
readme = "README.md"
homepage = "https://github.com/lparcq/procmon-oprs"
keywords = ["proc", "linux", "process", "monitor"]
categories = ["command-line-utilities"]
license = "GPL-3.0-or-later"
edition = "2018"

[[bin]]
name = "oprs"
path = "src/main.rs"

[dependencies]
anyhow = "1"
argh = "0.1"
chrono = "0.4"
console = "0"
ctrlc = { version = "3.0", features = ["termination"] }
itertools = "0.10"
libc = "0.2"
light-ini = "0.1"
log = "0"
memchr = "2"
nom = "7"
procfs = "0.14"
simplelog = "0.12"
strum = "0.24"
strum_macros = "0.24"
termion = "2"
tui = { version = "0.19", default-features = false, features = ['termion'] }
thiserror = "1.0"
xdg = "2"

[profile.release]
lto = 'thin'
panic = 'abort'
opt-level = 3
debug = false

[profile.dev]
opt-level = 0
debug = true
