[package]
name = "oprs"
version = "0.2.0"
authors = ["Laurent Pelecq <lpelecq+oprs@circoise.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "2"
config = "0"
console = "0"
libc = "0.2"
log = "0"
loggerv = "0"
procfs = "0.7"
structopt = "0.3"
structopt-derive = "0"
strum = "0.18"
strum_macros = "0.18"
thiserror = "1.0"
xdg = "2"
termion = "1.5"

[profile.release]
lto = true
panic = 'abort'
opt-level = 3
debug = false

[profile.dev]
opt-level = 0
debug = true

