[package]
name = "procmon-oprs"
version = "0.8.1"
authors = ["Laurent Pelecq <lpelecq+rust@circoise.eu>"]
description = "A process monitor for Linux"
readme = "README.md"
homepage = "https://github.com/lparcq/procmon-oprs"
keywords = ["proc", "linux", "process", "monitor"]
categories = ["command-line-utilities"]
license = "GPL-3.0-or-later"
edition = "2018"

[[bin]]
name = "oprs"
path = "src/main.rs"

[dependencies]
anyhow = "1"
argh = "0.1"
chrono = "0.4"
console = "0"
ctrlc = { version = "3.0", features = ["termination"] }
itertools = "0.9"
libc = "0.2"
light-ini = "0.1"
log = "0"
nom = "5"
procfs = "0.7"
simplelog = "0.7"
strum = "0.18"
strum_macros = "0.18"
termion = "1.5"
thiserror = "1.0"
xdg = "2"

[profile.release]
lto = true
panic = 'abort'
opt-level = 3
debug = false

[profile.dev]
opt-level = 0
debug = true

